import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import { UserPlaylists } from 'react-spotify-api'
import { Playlist } from 'react-spotify-api'
import { User } from 'react-spotify-api'


export default function Home({ authToken }) {
  console.log({ authToken })

  if (!authToken) return null;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Welcome
          <User>
            {(user, loading, error) => {
              console.log(user, loading, error)

              return user ? (
                <ul>
                  <li>{user?.data?.display_name}</li>
                </ul>
              ) : null
            }
            }
          </User>
        </h2>

        <h2>Your playlists</h2>
        <ul>
          <UserPlaylists>
            {
              (playlists, loading, error) => {
                console.log({ playlists, loading, error });
                if (loading) return (<h3>Loading...</h3>);
                if (error) return (<h3>{error}</h3>);

                if (!playlists) return null;

                return (
                  playlists?.data?.items?.map(playlist => (
                    <li key={playlist.id} >
                      <Link href={`/playlists/${playlist.id}`}><a>{playlist.name}</a></Link>
                    </li>
                  )) || null
                )
              }
            }
          </UserPlaylists>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
